---
- name: Transfer and execute a script.
  hosts: all
  remote_user: root
  become: yes
  tasks:
     - name: Transfer the script
       copy: src=reset_node.sh dest=/root mode=0777

     - name: Execute the script
       command: sh /root/reset_node.sh