  - name: Install screen
    hosts: all
    become: true
    tasks: 
     - name: install screen
       apt:
         name: screen
         state: present

  - name: Install zsh
    hosts: all
    become: true
    tasks: 
     - name: Install zsh
       apt:
         name: zsh
         state: present
  


       