---
- name: execute a script.
  hosts: "{{hostname}}"
  remote_user: root
  become: yes
  tasks:
     - name: Restore node into the proxmox physical node...
       ansible.builtin.shell: |
        qmrestore {{image}} {{vmid}} --storage {{storage}} --unique --force && 
        qm set {{vmid}} --name {{vmname}} &&
        qm start {{vmid}}