version: '3.5'
networks:
  cluster:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "192.168.0.0/24"

services:
  dns-server:
    restart: always
    image: jodafons/dns-server
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    volumes:
    - $HOME/volumes/dns-server:/data # Change volume path
    networks:
      cluster:
        ipv4_address: 192.168.0.100