version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "3000:1194/udp"
    restart: always
    volumes:
     - /mnt/market_place/volumes/openvpn:/etc/openvpn