version: "3"
services:
  web:
    image: "tbbrics/dorothy-image-service-web:v1.7.5"
    environment:
      PRODUCTION: true
    command: "./run_server.sh"
    volumes:
      - /home/brics/volumes/dorothy-image/data:/imagesrep
    restart: unless-stopped
    container_name: dorothy-image
  db:
    image: "postgres:13.0"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "R2E)5Dqd5ixizrU>+[mR"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data/postgres"
    volumes:
      - /home/brics/volumes/dorothy-image/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    container_name: db-dorothy-image
