---
- name: Transfer and execute a script.
  hosts: "{{host_name}}"
  remote_user: root
  become: yes
  tasks:
     - name: Execute the script
       ansible.builtin.shell: |
        qmrestore {{image}} {{vmid}} --storage local-lvm --unique --force && 
        qm set {{vmid}} --name {{node_name}} &&
        qm start {{vmid}}