version: "3"
services:
  www:
    image: "gabrielmilan/www-lps:main-4.0"
    volumes:
      - /mnt/homes:/home
    ports:
      - "80:80"
    restart: unless-stopped
    container_name: www



  paf:
    image: "gabrielmilan/www-lps:paf-4.0"
    ports:
      - "81:80"
    restart: unless-stopped
    container_name: paf


  virtuais:
    image: "gabrielmilan/www-lps:virtuais-4.0"
    volumes:
      - /mnt/homes:/home
    ports:
      - "82:80"
    restart: unless-stopped
    container_name: virtuais




