version: "3"
services:
  web:
    image: "tbbrics/dorothy-report-web:1.5.1"
    environment:
      IMAGE_SERVICE_HOST: "https://dorothy-image.lps.ufrj.br"
      IMAGE_SERVICE_TOKEN: "bce9e5011729456a562ff94bf3c5d5069c9ea54c"
      PRODUCTION: true
    command: "./run_server.sh"
    volumes:
      - /mnt/volumes/dorothy__dorothy-imagesrep-nfs:/imagesrep
    networks:
      - npm
    restart: unless-stopped
    container_name: dorothy
  db:
    image: "postgres:13.0"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "R2E)5Dqd5ixizrU>+[mR"
      POSTGRES_USER: "postgres"
      PGDATA: "/var/lib/postgresql/data/postgres"
    volumes:
      - /mnt/volumes/dorothy__postgresdb:/var/lib/postgresql/data
    networks:
      - npm
    restart: unless-stopped
    container_name: db-dorothy
networks:
  npm:
    name: npm
    external: true
