---
- name: create node.
  hosts: "{{hosts}}"
  serial: 1
  remote_user: root
  become: yes
  tasks:
     - name: Add new node into the cluster
       ansible.builtin.shell: |
        echo "pvecm add {{ip_address}} --votes 0 --force" > run.sh &&
        (echo '{{master_key}}'; echo yes) | bash run.sh
