---
- name: Reset all nodes into the cluster
  hosts: "{{hostgroup}}"
  remote_user: root
  become: yes
  tasks:

     - name: Install GPU configuration...
       ansible.builtin.shell: |
        wget 
